language: node_js
node_js:
  - "10.1.0"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - CC_TEST_REPORTER_ID=147f28703d3ae0d7c498d8dbedbcb1adb912ffb4873e0b0c644fb78346404a93
    - PGPORT=5433
    - NODE_ENV=test
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - chmod 0755 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build:client
script:
  - npm run migrate:test
  - npm run test:server
  - mv ./coverage/lcov.info ./coverage/lcov.server.info
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.server.info --output ./coverage/codeclimate.server.json
  - npm run test:client
  - mv ./coverage/lcov.info ./coverage/lcov.client.info
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.client.info  --output ./coverage/codeclimate.client.json
  - ./cc-test-reporter sum-coverage -p 2 ./coverage/codeclimate.server.json ./coverage/codeclimate.client.json
  - ./cc-test-reporter upload-coverage
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT